apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j4blk646r-python
  janus-idp.io/tekton: j4blk646r-python
  backstage.io/kubernetes-id: j4blk646r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j4blk646r-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
